### PR TITLE
porn: add a note

### LINKED ISSUE #33: Update porn command
Update the porn command with text saying you have to login to vote for the noobs to read ;)

### PR DESCRIPTION
**Pull request by tilda**
xd (fixes #33 )

### CODE REVIEW

**Comment by iamhansen** [comment]
owo whats this

**Comment by tilda** [comment]
note: I fucking hate conflicts

**Comment by melmsie** [comment]
what is this for, again?

**Comment by tilda** [comment]
This PR adds a note that says "Hey you have to login to vote" basically

**Comment by melmsie** [comment]
We actually removed the upvote requirement :)

**Comment by tilda** [comment]
oh ok

**Pull request closed without merging**
