### PR TITLE
Update memer.js

### PR DESCRIPTION
**Pull request by Xevryll**
You forgot one website for bot statistics.

### CODE REVIEW

**Comment by Aetheryx** [comment]
LGTM :^)

**Comment by Xevryll** [comment]
you need to fix rust.js :REEEEEEE:

**Comment by melmsie** [comment]
Get your bad memes outta here

**Comment by Xevryll** [comment]
Reopen this bitch

**Comment by Aetheryx** [comment]
no u

**Comment by Xevryll** [comment]
no u

**Pull request closed without merging**
